# --- Ubidots Configuration ---
UBIDOTS_TOKEN = "Masukkan_Token_Ubidots_Anda_Di_Sini"
UBIDOTS_DEVICE = "smallow" # Ganti jika nama device berbeda
UBIDOTS_VARS = "temperature,humidity,FSR" # Pastikan variabel ini ada di device
LOCAL_TZ = "Asia/Jakarta" # Zona waktu lokal

# --- MongoDB Atlas Configuration (Opsional untuk backup) ---
MONGO_URI = "mongodb+srv://user:pass@cluster.mongoserver.net/?retryWrites=true&w=majority"
MONGO_DB = "smallow"
MONGO_COLL = "sensor_data"
